### ISSUE TITLE
Incorrect dimension of `hyperSphere`

### ISSUE THREAD

**Issue by catanzaromj** [scikit-learn-contrib/scikit-dimension#16]
The parameter `d` in `skdim.datasets.hyperSphere` is documented to be the "Dimension of the hypersphere". However, it is actually one larger than the intrinsic dimension of the hypersphere--the parameter `d` is the dimension of the ambient space in which the hypersphere is embedded (extrinsic dimension).

```python
In [1]: from skdim.datasets import hyperSphere

In [2]: X = hyperSphere(n=100,d=2)

In [3]: X.shape
Out[3]: (100, 2)
```
The 2-sphere (the usual sphere) can't be embedded in R^2. The dataset `X` above is a sampling of the circle (1-sphere) not a 2-sphere.

**Comment by j-bac** [comment]
Thanks for pointing this out. `hyperSphere(n=100,d=1)` now returns the results you had with `hyperSphere(n=100,d=2)`.
