### ISSUE TITLE
[minor] Incorrect docstring for dataset `lineDiskBall`

### ISSUE THREAD

**Issue by JesseCresswell** [scikit-learn-contrib/scikit-dimension#20]
https://github.com/scikit-learn-contrib/scikit-dimension/blob/bde433aba866eafdf4de3bf2c7b226f68a7dd1cf/skdim/datasets.py#L139
Docstring for `lineDiskBall` says return value is an `np.array`, but actually a tuple with two elements is returned.

**Comment by j-bac** [comment]
done
