### ISSUE TITLE
Computation of estimator values pointwise on kNN sets is not parallelized

### ISSUE THREAD

**Issue by JesseCresswell** [scikit-learn-contrib/scikit-dimension#21]
I will use ESS as an example, since it is a pretty slow estimator. Since it is a `LocalEstimator`, when `fit` is called kNNs are first computed (if not already provided)
https://github.com/scikit-learn-contrib/scikit-dimension/blob/b9e8845123b8396fc4b078d4f68271d5a568a7f7/skdim/_commonfuncs.py#L419
and this in turn calls to the sklearn library which properly parallelizes the computation based on the parameter `n_jobs` that we can provide.

Second, a call to `self.fit` in the `ESS` class performs a simple, single-threaded `for` loop over the datapoints.
https://github.com/scikit-learn-contrib/scikit-dimension/blob/b9e8845123b8396fc4b078d4f68271d5a568a7f7/skdim/id/_ESS.py#L75-L78
The computations are "embarrassingly parallel". I have locally implemented parallelization and seen at least a 6x speedup in ESS computation on datasets of size 5,000 - 50,000.

I can open a PR with these changes as an example if you are willing to add `joblib` as a dependency.

**Comment by j-bac** [comment]
Makes sense and sounds like an awesome speedup! ESS is currently one of the slowest estimators but the same strategy might work for others. Please feel free to open a PR, joblib is already a dependency since it is used by sklearn. We can probably replace multiprocessing with joblib everywhere.

**Comment by JesseCresswell** [comment]
Closed by PR https://github.com/scikit-learn-contrib/scikit-dimension/pull/24
