### ISSUE TITLE
Support numpy 2.0?

### ISSUE THREAD

**Issue by catanzaromj** [scikit-learn-contrib/scikit-dimension#29]
Is it possible to support numpy versions 2.0.0 and above? When I try to run `skdim` in a conda environment with a newer version of numpy, I get the following:

```python
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

I see the pin of `numpy<=1.20` in `requirements.txt` but it's unclear to me why this is pinned down. I can build scikit-dimension fine with `numpy==2.0.1` locally.

**Comment by j-bac** [comment]
I forgot myself which error prompted me to pin back then. I updated requirements.txt and will have to make a new release

**Comment by catanzaromj** [comment]
Awesome, thanks for the quick response and helpful package!
